# Generated by Django 5.2.4 on 2025-07-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="departments",
            field=models.ManyToManyField(
                blank=True, to="users.department", verbose_name="所属部门"
            ),
        ),
    ]
